linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - nakedret
    - funlen
    - wsl
    - gocognit
    - gomnd
    - nlreturn
    - goerr113
    - testpackage
    - nestif
    - godot
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - goconst
        - errcheck
    - text: "G401:" # Use of weak cryptographic primitive
      linters:
        - gosec
    - text: "G505:" # weak cryptographic primitive
      linters:
        - gosec
    - path: internal/mse/
      linters:
        - gosec
